---
title: "atelier 4"
author: "thomas vangrevelynghe"
date: "13/11/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
nutriage <- read.csv("C:/Users/thoma/Desktop/Atelier4-master/nutriage.csv")
names(nutriage)
```

## Option 1

```{r}
hist(nutriage$taille)
summary(nutriage$taille)
```

H: taille $\sim N(\mu,\sigma)$ le problème est $\Pr(taille < 0) >0$

```{r}
mean(nutriage$taille)
sd (nutriage$taille)
```

calculer $\(taille < 0)$ avec $taille \sim N(163.9602,9.003368)$

```{r}
pnorm(0,mean(nutriage$taille),sd(nutriage$taille))
```


## Option 2

Soit $taille = e^x$ avec $x \sim N(mu,\sigma).$ Alors $x = ln(taille)

```{r}
x <- log(nutriage$taille)
hist(x)
```



```{r}
x <- log(nutriage$taille)
hist(x)
summary(x)
Q <- seq(from=0,to=1,by=0.1)
Q
qnorm(Q)

```

qq-plot

```{r}
z <- (x-mean(x))/sd(x)
n <- length(z)
n
Normal <- rnorm(n)
qqplot(Normal,z, xlim=c(-3,3),ylim=c(-3,3))
par (new=T)
plot(z,z,type="l",col="red",xlim=c(-3,3),ylim=c(-3,3),xlabel="",ylabel="")
```














## Option 1


```{r}
hist(nutriage$poids)
summary(nutriage$poids)
```

H: poids $\sim N(\mu,\sigma)$ le problème est $\Pr(taille < 0) >0$

```{r}
mean(nutriage$poids)
sd (nutriage$poids)
```

calculer $\(poids < 0)$ avec $poids \sim N(163.9602,9.003368)$

```{r}
pnorm(0,mean(nutriage$poids),sd(nutriage$poids))
```


## Option 2

Soit $poids = e^x$ avec $x \sim N(mu,\sigma).$ Alors $x = ln(poids)

```{r}
x <- log(nutriage$poids)
hist(x)
```



```{r}
x <- log(nutriage$poids)
hist(x)
summary(x)
Q <- seq(from=0,to=1,by=0.1)
Q
qnorm(Q)

```

qq-plot

```{r}
z <- (x-mean(x))/sd(x)
n <- length(z)
n
Normal <- rnorm(n)
qqplot(Normal,z, xlim=c(-3,3),ylim=c(-3,3), xlab = "Normal",ylab="log(poids)")
par (new=T)
plot(z,z,type="l",col="red",xlim=c(-3,3),ylim=c(-3,3),xlab="",ylab="")
```



cafe

```{r}
table(nutriage$cafe)
mean(nutriage$cafe)
var(nutriage$cafe)
lambda <- (mean(nutriage$cafe)+var(nutriage$cafe))/2
lambda
simul <- rpois(1000,lambda)
table(simul)
```



